# Generated by Django 4.2.1 on 2023-06-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelPlanning',
            fields=[
                ('delplanning_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('delplanning_id_origin', models.CharField(max_length=10, verbose_name='Id')),
                ('delplanning_title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('delplanning_goals_1', models.CharField(max_length=200, null=True, verbose_name='Meta 1')),
                ('delplanning_status_1', models.CharField(choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status')),
                ('delplanning_goals_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta 2')),
                ('delplanning_status_2', models.CharField(choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status')),
                ('delplanning_goals_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta 3')),
                ('delplanning_status_3', models.CharField(choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status')),
                ('delplanning_progess', models.IntegerField(blank=True, default=0, null=True, verbose_name='Progresso')),
                ('delplanning_final_date_origin', models.DateField(verbose_name='Data final')),
                ('delplanning_description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('delplanning_resource', models.CharField(max_length=100, verbose_name='Recursos')),
                ('delplanning_contributor_name', models.CharField(max_length=45, verbose_name='Nome do colaborador')),
                ('delplanning_creator', models.CharField(max_length=50, verbose_name='Criador')),
                ('delplanning_date', models.DateField(verbose_name='Data de deleçao')),
                ('delplanning_browser', models.CharField(max_length=50, verbose_name='Navegador')),
                ('delplanning_ip', models.CharField(max_length=50, verbose_name='Ip da máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('planning_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_title', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('planning_goals_1', models.CharField(max_length=200, null=True, verbose_name='Meta 1')),
                ('planning_status_1', models.CharField(max_length=20, null=True, verbose_name='Status 1')),
                ('planning_goals_2', models.CharField(max_length=200, null=True, verbose_name='Meta 2')),
                ('planning_status_2', models.CharField(max_length=20, null=True, verbose_name='Status 2')),
                ('planning_goals_3', models.CharField(max_length=200, null=True, verbose_name='Meta 3')),
                ('planning_status_3', models.CharField(max_length=20, null=True, verbose_name='Status 3')),
                ('planning_progess', models.CharField(max_length=1, null=True, verbose_name='Progresso')),
                ('planning_final_date', models.CharField(null=True, verbose_name='Data final')),
                ('planning_description', models.CharField(max_length=300, null=True, verbose_name='Descrição')),
                ('planning_resource', models.CharField(max_length=100, null=True, verbose_name='Recursos')),
                ('planning_contributor_name', models.CharField(max_length=45, null=True, verbose_name='Nome do colaborador')),
                ('planning_creator', models.CharField(max_length=50, null=True, verbose_name='Criador')),
                ('planning_date', models.CharField(null=True, verbose_name='Data/Hora')),
            ],
        ),
    ]
