# Generated by Django 4.2.1 on 2023-07-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('planning_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_name_manager', models.CharField(max_length=50, verbose_name='Nome do Gerente')),
                ('planning_name_collaborator', models.CharField(max_length=50, verbose_name='Nome do Colaborador')),
                ('planning_title', models.CharField(max_length=100, verbose_name='Título')),
                ('planning_goals', models.CharField(max_length=200, verbose_name='Meta')),
                ('planning_status', models.CharField(max_length=100, verbose_name='Status')),
                ('planning_progess', models.CharField(max_length=100, verbose_name='Progresso')),
                ('planning_description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('planning_resource', models.CharField(max_length=100, verbose_name='Recursos')),
                ('planning_date', models.CharField(verbose_name='Data')),
                ('planning_hour', models.CharField(verbose_name='Hora')),
                ('planning_final_date', models.CharField(verbose_name='Data final')),
                ('planning_final_hour', models.CharField(verbose_name='Hora final')),
                ('planning_collaborator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usercollaborator')),
                ('planning_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermanager')),
            ],
        ),
    ]
