# Generated by Django 4.2.1 on 2023-08-09 18:31

from django.db import migrations, models
import pdi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='planning_date',
            field=models.CharField(default=pdi.models.Planning.data, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='planning_description',
            field=models.CharField(default='EM ANDAMENTO', max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='planning_hour',
            field=models.CharField(default=pdi.models.Planning.time, verbose_name='Hora'),
        ),
    ]
