# Generated by Django 4.2.1 on 2023-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_goals_9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_10',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_4',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_5',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_6',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_7',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_8',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='delplanning',
            name='delplanning_status_9',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_goals_9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta 3'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_10',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_4',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_5',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_6',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_7',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_8',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status_9',
            field=models.CharField(blank=True, choices=[('1', 'Concluido'), ('2', 'Em atraso'), ('3', 'Em andamento')], max_length=1, verbose_name='status'),
        ),
    ]
