# Generated by Django 4.2.1 on 2023-06-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='planning_goals',
            field=models.CharField(max_length=150, null=True, verbose_name='Meta 1'),
        ),
    ]
