# Generated by Django 4.2.1 on 2023-06-01 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='planning_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
    ]
