# Generated by Django 4.2.1 on 2023-06-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='planning_goals_1',
            new_name='planning_goals',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='planning_status_1',
            new_name='planning_status',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='planning_goals_2',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='planning_goals_3',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='planning_status_2',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='planning_status_3',
        ),
    ]
