# Generated by Django 4.2.1 on 2023-08-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0002_alter_planning_planning_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='planning_description',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='planning_status',
            field=models.CharField(default='EM ANDAMENTO', max_length=100, verbose_name='Status'),
        ),
    ]
