# Generated by Django 4.2.1 on 2023-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0003_alter_planning_planning_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='planning_progess',
            field=models.IntegerField(verbose_name='Progresso'),
        ),
    ]
