# Generated by Django 4.2.1 on 2023-06-16 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteFeedback',
            fields=[
                ('delete_feedback_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID DE EXCLUSAO')),
                ('delete_feedback_date_time_end', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA DA EXCLUSÃO')),
                ('delete_feedback_ipadress', models.CharField(max_length=20, verbose_name='IP')),
                ('delete_feedback_browser', models.CharField(max_length=20, verbose_name='NAVEGADOR')),
                ('delete_feedback_iduser', models.CharField(max_length=50, verbose_name='ID DO FEEBACK')),
                ('delete_feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('delete_feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('delete_feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('delete_feedback_desc', models.CharField(max_length=350, verbose_name='DESCRIÇÃO')),
                ('delete_feedback_date_time', models.DateTimeField(blank=True, db_index=True, verbose_name='DATA/HORA')),
                ('delete_feedback_evaluate', models.IntegerField(default=0, verbose_name='ESTRELAS')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('feedback_desc', models.CharField(max_length=350, verbose_name='DESCRIÇÃO')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='AVALIAÇÃO')),
            ],
        ),
    ]
