# Generated by Django 4.2.1 on 2023-06-20 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('feedback_desc', models.CharField(max_length=350, verbose_name='DESCRIÇÃO')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='AVALIAÇÃO')),
            ],
        ),
    ]
