# Generated by Django 4.2.1 on 2023-05-29 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteFeedback',
            fields=[
                ('delete_feedback_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_feedback_iduser', models.CharField(max_length=50, verbose_name='ID DO FEEBACK')),
                ('delete_feedback_author', models.CharField(max_length=50, verbose_name='AUTOR')),
                ('delete_feedback_receiver', models.CharField(max_length=50, verbose_name='RECEPTO')),
                ('delete_feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('delete_feedback_description', models.CharField(max_length=500, verbose_name='DESCRIÇÃO')),
                ('delete_feedback_date_time', models.DateTimeField(blank=True, db_index=True, verbose_name='DATA/HORA')),
                ('delete_feedback_evaluate', models.IntegerField(default=0, verbose_name='ESTRELAS')),
                ('delete_feedback_date_time_end', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA DA EXCLUSÃO')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_author', models.CharField(max_length=50, verbose_name='autor')),
                ('feedback_receiver', models.CharField(max_length=50, verbose_name='receptor')),
                ('feedback_title', models.CharField(max_length=50, verbose_name='titulo')),
                ('feedback_description', models.CharField(max_length=900, verbose_name='descricao')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='data/hora')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='estrelas')),
            ],
        ),
    ]
