# Generated by Django 4.2.1 on 2023-06-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.CharField(verbose_name='DATA/HORA'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.CharField(default=0, verbose_name='AVALIAÇÃO'),
        ),
    ]
