# Generated by Django 4.2.1 on 2023-08-29 00:24

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.CharField(default=feedback.models.Feedback.data, verbose_name='DATA'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_hour',
            field=models.CharField(default=feedback.models.Feedback.time, verbose_name='HORA'),
        ),
    ]
