# Generated by Django 4.2.1 on 2023-06-01 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletefeedback',
            name='delete_feedback_description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_description',
        ),
        migrations.AddField(
            model_name='deletefeedback',
            name='delete_feedback_browser',
            field=models.CharField(default='', max_length=20, verbose_name='NAVEGADOR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletefeedback',
            name='delete_feedback_desc',
            field=models.CharField(default='', max_length=350, verbose_name='DESCRIÇÃO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletefeedback',
            name='delete_feedback_ipadress',
            field=models.CharField(default='', max_length=20, verbose_name='IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_desc',
            field=models.CharField(default='', max_length=350, verbose_name='DESCRIÇÃO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletefeedback',
            name='delete_feedback_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID DE EXCLUSAO'),
        ),
        migrations.AlterField(
            model_name='deletefeedback',
            name='delete_feedback_receiver',
            field=models.CharField(max_length=50, verbose_name='DESTINATARIO'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author',
            field=models.CharField(max_length=50, verbose_name='AUTOR'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.IntegerField(default=0, verbose_name='AVALIAÇÃO'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_receiver',
            field=models.CharField(max_length=50, verbose_name='DESTINATARIO'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_title',
            field=models.CharField(max_length=50, verbose_name='TITULO'),
        ),
    ]
