# Generated by Django 4.2.1 on 2023-06-20 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteFeedbackC',
            fields=[
                ('delete_feedback_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID DE EXCLUSAO')),
                ('delete_feedback_date_time_end', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA DA EXCLUSÃO')),
                ('delete_feedback_ipadress', models.CharField(max_length=20, verbose_name='IP')),
                ('delete_feedback_browser', models.CharField(max_length=20, verbose_name='NAVEGADOR')),
                ('delete_feedback_iduser', models.CharField(max_length=50, verbose_name='ID DO FEEBACK')),
                ('delete_feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('delete_feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('delete_feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('delete_feedback_quest1', models.CharField(max_length=100, verbose_name='Sobre o tempo e o Horario da Reuniao, avalie')),
                ('delete_feedback_quest2', models.CharField(max_length=100, verbose_name='Sobre o conteúdo, pauta abordada avalie')),
                ('delete_feedback_quest3', models.CharField(max_length=100, verbose_name='deixe aqui sua sugestão ou elogio para melhorarmos nas próximas reuniões')),
                ('delete_feedback_note', models.CharField(max_length=350, verbose_name='ANOTAÇÃO')),
                ('delete_feedback_date_time', models.DateTimeField(blank=True, db_index=True, verbose_name='DATA/HORA')),
                ('delete_feedback_evaluate', models.IntegerField(default=0, verbose_name='ESTRELAS')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteFeedbackG',
            fields=[
                ('delete_feedback_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID DE EXCLUSAO')),
                ('delete_feedback_date_time_end', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA DA EXCLUSÃO')),
                ('delete_feedback_ipadress', models.CharField(max_length=20, verbose_name='IP')),
                ('delete_feedback_browser', models.CharField(max_length=20, verbose_name='NAVEGADOR')),
                ('delete_feedback_iduser', models.CharField(max_length=50, verbose_name='ID DO FEEBACK')),
                ('delete_feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('delete_feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('delete_feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('delete_feedback_quest1', models.CharField(max_length=100, verbose_name='Quais são as habilidades de seu liderado?')),
                ('delete_feedback_quest2', models.CharField(max_length=100, verbose_name='Qual seu diferencial?')),
                ('delete_feedback_quest3', models.CharField(max_length=100, verbose_name='O que impede seu desenvolvimento?')),
                ('delete_feedback_quest4', models.CharField(max_length=100, verbose_name='O que pode melhorar?')),
                ('delete_feedback_quest5', models.CharField(max_length=100, verbose_name='Quais mudanças pode melhorar seu desempenho?')),
                ('delete_feedback_quest6', models.CharField(max_length=100, verbose_name='O que pode atrapalhar seu desempenho?')),
                ('delete_feedback_note', models.CharField(max_length=350, verbose_name='ANOTAÇÃO')),
                ('delete_feedback_date_time', models.DateTimeField(blank=True, db_index=True, verbose_name='DATA/HORA')),
                ('delete_feedback_evaluate', models.IntegerField(default=0, verbose_name='ESTRELAS')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackC',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('feedback_quest1', models.CharField(max_length=100, verbose_name='Sobre o tempo e o Horario da Reuniao, avalie')),
                ('feedback_quest2', models.CharField(max_length=100, verbose_name='sobre o conteúdo, pauta abordada avalie')),
                ('feedback_quest3', models.CharField(max_length=100, verbose_name='deixe aqui sua sugestão ou elogio para melhorarmos nas próximas reuniões')),
                ('feedback_note', models.CharField(max_length=350, verbose_name='ANOTAÇÃO')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='AVALIAÇÃO')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackG',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('feedback_quest1', models.CharField(max_length=100, verbose_name='Quais são as habilidades de seu liderado?')),
                ('feedback_quest2', models.CharField(max_length=100, verbose_name='Qual seu diferencial?')),
                ('feedback_quest3', models.CharField(max_length=100, verbose_name='O que impede seu desenvolvimento?')),
                ('feedback_quest4', models.CharField(max_length=100, verbose_name='O que pode melhorar?')),
                ('feedback_quest5', models.CharField(max_length=100, verbose_name='Quais mudanças pode melhorar seu desempenho?')),
                ('feedback_quest6', models.CharField(max_length=100, verbose_name='O que pode atrapalhar seu desempenho?')),
                ('feedback_note', models.CharField(max_length=350, verbose_name='ANOTAÇÃO')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='AVALIAÇÃO')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
