# Generated by Django 4.2.1 on 2023-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_deletefeedbackc_deletefeedbackg_feedbackc_feedbackg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletefeedbackg',
            name='delete_feedback_evaluate',
            field=models.CharField(default=0, verbose_name='ESTRELAS'),
        ),
    ]
