# Generated by Django 4.2.1 on 2023-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.CharField(default=0, max_length=2, verbose_name='AVALIAÇÃO'),
        ),
    ]
