# Generated by Django 4.2.1 on 2023-06-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_delschedule_delschedule_dt_now'),
        ('feedback', '0002_remove_deletefeedback_delete_feedback_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='schedule_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
    ]
