# Generated by Django 4.2.1 on 2023-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_feedback_evaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.CharField(verbose_name='DATA'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.CharField(max_length=2, verbose_name='AVALIAÇÃO'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_hour',
            field=models.CharField(verbose_name='HORA'),
        ),
    ]
