# Generated by Django 4.2.1 on 2023-06-21 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_deletefeedbackg_delete_feedback_evaluate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.CharField(max_length=50, verbose_name='TITULO')),
                ('feedback_manage', models.CharField(max_length=50, verbose_name='GERENTE')),
                ('feedback_collaborator', models.CharField(max_length=50, verbose_name='COLABORADOR')),
                ('feedback_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('feedback_desc', models.CharField(max_length=350, verbose_name='ANOTAÇÃO')),
                ('feedback_evaluate', models.IntegerField(default=0, verbose_name='AVALIAÇÃO')),
            ],
        ),
        migrations.DeleteModel(
            name='DeleteFeedbackC',
        ),
        migrations.DeleteModel(
            name='DeleteFeedbackG',
        ),
        migrations.DeleteModel(
            name='FeedbackC',
        ),
        migrations.DeleteModel(
            name='FeedbackG',
        ),
    ]
