# Generated by Django 4.2.1 on 2023-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.CharField(max_length=50, verbose_name='AVALIAÇÃO'),
        ),
    ]
