# Generated by Django 4.2.1 on 2023-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_delete_deletefeedbackc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_evaluate',
            field=models.CharField(max_length=1, verbose_name='AVALIAÇÃO'),
        ),
    ]
