# Generated by Django 4.2.1 on 2023-06-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_feedback_evaluate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_desc',
            new_name='feedback_note',
        ),
    ]
