# Generated by Django 4.2.1 on 2023-06-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_delschedule_delschedule_dt_now'),
        ('feedback', '0006_rename_feedback_desc_feedback_feedback_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_idschedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
    ]
