# Generated by Django 4.2.1 on 2023-08-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('schedule_name_manager', models.CharField(max_length=100, verbose_name='Nome do Gerente')),
                ('schedule_name_collaborator', models.CharField(max_length=100, verbose_name='Nome do Colaborador')),
                ('schedule_topic', models.CharField(max_length=50, verbose_name='Título')),
                ('schedule_date', models.CharField(verbose_name='Data')),
                ('schedule_hour', models.CharField(verbose_name='Hora')),
                ('schedule_meet_location', models.CharField(max_length=100, verbose_name='Local da Reunião')),
                ('schedule_description', models.CharField(max_length=350, verbose_name='Descrição')),
                ('schedule_duration', models.CharField(max_length=2, verbose_name='Duração')),
                ('schedule_status', models.BooleanField(default=False, verbose_name='STATUS')),
                ('schedule_collaborator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usercollaborator')),
                ('schedule_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermanager')),
            ],
        ),
    ]
