# Generated by Django 4.2.1 on 2023-06-14 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelSchedule',
            fields=[
                ('delschedule_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('delschedule_topic', models.CharField(max_length=30, verbose_name='Tópico')),
                ('delschedule_date_hour', models.DateTimeField(verbose_name='Data Hora inicial')),
                ('delschedule_name_creator', models.CharField(max_length=100, verbose_name='Nome do criador')),
                ('delschedule_name_receiver', models.CharField(max_length=100, verbose_name='Nome do recebidor')),
                ('delschedule_meet_link', models.URLField(max_length=150, verbose_name='Link de reunião')),
                ('delschedule_meet_location', models.CharField(max_length=50, verbose_name='Local da Reunião')),
                ('delschedule_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('delschedule_duration', models.CharField(choices=[('30:00', '30:00'), ('01:00:00', '1:00:00'), ('01:30:00', '1:30:00'), ('02:00:00', '2:00:00'), ('02:30:00', '2:30:00'), ('03:00:00', '3:00:00')], default='30:00', max_length=8, verbose_name='Duração')),
                ('delschedule_dt_now', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 1, 26, 27, 769502), verbose_name='Data e hora atuais')),
                ('delschedule_ip', models.CharField(max_length=50, verbose_name='Ip')),
                ('delschedule_browser', models.CharField(max_length=100, verbose_name='Browser')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('schedule_topic', models.CharField(max_length=30, verbose_name='Título')),
                ('schedule_date_hour', models.CharField(verbose_name='Data Hora inicial')),
                ('schedule_name_creator', models.CharField(max_length=100, verbose_name='Nome do criador')),
                ('schedule_name_receiver', models.CharField(max_length=100, verbose_name='Nome do recebidor')),
                ('schedule_meet_link', models.URLField(max_length=255, verbose_name='Link de reunião')),
                ('schedule_meet_location', models.CharField(max_length=100, verbose_name='Local da Reunião')),
                ('schedule_description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('schedule_duration', models.CharField(max_length=8, verbose_name='Duração')),
            ],
        ),
    ]
