# Generated by Django 4.2.1 on 2023-05-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteSchedule',
            fields=[
                ('schedule_delete_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('schedule_delete_topic', models.CharField(max_length=50, verbose_name='Tópico')),
                ('schedule_delete_date_hour', models.DateTimeField(verbose_name='Data Hora inicial')),
                ('schedule_delete_name_creator', models.CharField(max_length=100, verbose_name='Nome do criador')),
                ('schedule_delete_name_receiver', models.CharField(max_length=100, verbose_name='Nome do recebidor')),
                ('schedule_delete_meet_link', models.URLField(max_length=250, verbose_name='Link de reunião')),
                ('schedule_delete_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('schedule_delete_duration', models.CharField(choices=[('30:00', '30:00'), ('45:00', '45:00'), ('01:00:00', '1:00:00')], default='30:00', max_length=8, verbose_name='Duração')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('schedule_topic', models.CharField(max_length=50, verbose_name='Tópico')),
                ('schedule_date_hour', models.DateTimeField(verbose_name='Data Hora inicial')),
                ('schedule_name_creator', models.CharField(max_length=100, verbose_name='Nome do criador')),
                ('schedule_name_receiver', models.CharField(max_length=100, verbose_name='Nome do recebidor')),
                ('schedule_meet_link', models.URLField(max_length=250, verbose_name='Link de reunião')),
                ('schedule_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('schedule_duration', models.CharField(choices=[('30:00', '30:00'), ('45:00', '45:00'), ('01:00:00', '1:00:00')], default='30:00', max_length=8, verbose_name='Duração')),
            ],
        ),
    ]
