# Generated by Django 4.2.1 on 2023-06-20 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 18, 27, 4, 675524), verbose_name='Data e hora atuais'),
        ),
    ]
