# Generated by Django 4.2.1 on 2023-08-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_description',
            field=models.CharField(max_length=350, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_duration',
            field=models.CharField(max_length=2, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_topic',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
