# Generated by Django 4.2.1 on 2023-08-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.CharField(choices=[('0', 'NÃO FINALIZADA'), ('1', 'FINALIZADA')], max_length=1, verbose_name='Status'),
        ),
    ]
