# Generated by Django 4.2.1 on 2023-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
