# Generated by Django 4.2.1 on 2023-05-29 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_deleteschedule_schedule_delete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_delete_date_hour_now',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 19, 58, 41, 575723), verbose_name='Data e hora atuais'),
        ),
    ]
