# Generated by Django 4.2.1 on 2023-06-20 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 19, 48, 43, 991535), verbose_name='Data e hora atuais'),
        ),
    ]
