# Generated by Django 4.2.1 on 2023-08-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.CharField(choices=[('NÃO FINALIZADA', '0'), ('FINALIZADA', '1')], max_length=20, verbose_name='Status'),
        ),
    ]
