# Generated by Django 4.2.1 on 2023-05-29 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_deleteschedule_schedule_delete_date_hour_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_date_hour_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 0, 16, 555981), verbose_name='Data e hora atuais'),
        ),
    ]
