# Generated by Django 4.2.1 on 2023-05-29 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_deleteschedule_schedule_delete_date_hour_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteschedule',
            name='schedule_delete_date_hour_now',
        ),
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_browser',
            field=models.CharField(default=' ', max_length=150, verbose_name='browser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_dt_hr_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 14, 58, 65181), verbose_name='Data e hora atuais'),
        ),
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_ip',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
