# Generated by Django 4.2.1 on 2023-05-31 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_deleteschedule_schedule_delete_date_hour_now_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteschedule',
            name='schedule_browser',
        ),
        migrations.RemoveField(
            model_name='deleteschedule',
            name='schedule_ip',
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_dt_hr_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 14, 22, 49, 307686), verbose_name='Data e hora atuais'),
        ),
    ]
