<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-16 00:30
=======
# Generated by Django 4.2.1 on 2023-06-20 14:04
>>>>>>> 66f2522497b989cc68a5a64fc35a9d553fd9cd2e

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 21, 30, 36, 29206), verbose_name='Data e hora atuais'),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 11, 4, 55, 28381), verbose_name='Data e hora atuais'),
>>>>>>> 66f2522497b989cc68a5a64fc35a9d553fd9cd2e
        ),
    ]
