# Generated by Django 4.2.1 on 2023-06-01 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_deleteschedule_schedule_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_delete_browser',
            field=models.CharField(default=' ', max_length=100, verbose_name='Browser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_delete_ip',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteschedule',
            name='schedule_meet_location',
            field=models.CharField(default=' ', max_length=50, verbose_name='Local da Reunião'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_meet_location',
            field=models.CharField(default=' ', max_length=50, verbose_name='Local da Reunião'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_duration',
            field=models.CharField(choices=[('30:00', '30:00'), ('01:00:00', '1:00:00'), ('01:30:00', '1:30:00'), ('02:00:00', '2:00:00'), ('02:30:00', '2:30:00'), ('03:00:00', '3:00:00')], default='30:00', max_length=8, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_meet_link',
            field=models.URLField(max_length=150, verbose_name='Link de reunião'),
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_delete_topic',
            field=models.CharField(max_length=30, verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='deleteschedule',
            name='schedule_dt_hr_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 21, 20, 34, 435717), verbose_name='Data e hora atuais'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_duration',
            field=models.CharField(choices=[('30:00', '30:00'), ('01:00:00', '1:00:00'), ('01:30:00', '1:30:00'), ('02:00:00', '2:00:00'), ('02:30:00', '2:30:00'), ('03:00:00', '3:00:00')], default='30:00', max_length=8, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_meet_link',
            field=models.URLField(max_length=150, verbose_name='Link de reunião'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_topic',
            field=models.CharField(max_length=30, verbose_name='Tópico'),
        ),
    ]
