# Generated by Django 4.2.1 on 2023-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.IntegerField(choices=[(1, 'NÃO FINALIZADA'), (2, 'FINALIZADA')], verbose_name='Status'),
        ),
    ]
