# Generated by Django 4.2.1 on 2023-06-01 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_deleteschedule_schedule_delete_browser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelSchedule',
            fields=[
                ('scheduledel_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('scheduledel_topic', models.CharField(max_length=30, verbose_name='Tópico')),
                ('scheduledel_date_hour', models.DateTimeField(verbose_name='Data Hora inicial')),
                ('scheduledel_name_creator', models.CharField(max_length=100, verbose_name='Nome do criador')),
                ('scheduledel_name_receiver', models.CharField(max_length=100, verbose_name='Nome do recebidor')),
                ('scheduledel_meet_link', models.URLField(max_length=150, verbose_name='Link de reunião')),
                ('scheduledel_meet_location', models.CharField(max_length=50, verbose_name='Local da Reunião')),
                ('scheduledel_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('scheduledel_duration', models.CharField(choices=[('30:00', '30:00'), ('01:00:00', '1:00:00'), ('01:30:00', '1:30:00'), ('02:00:00', '2:00:00'), ('02:30:00', '2:30:00'), ('03:00:00', '3:00:00')], default='30:00', max_length=8, verbose_name='Duração')),
                ('scheduledel_dt_now', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 21, 54, 9, 176711), verbose_name='Data e hora atuais')),
                ('scheduledel_ip', models.CharField(max_length=50, verbose_name='Ip')),
                ('scheduledel_browser', models.CharField(max_length=100, verbose_name='Browser')),
            ],
        ),
        migrations.DeleteModel(
            name='DeleteSchedule',
        ),
    ]
