# Generated by Django 4.2.1 on 2023-06-01 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_delschedule_delete_deleteschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_browser',
            new_name='delschedule_browser',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_date_hour',
            new_name='delschedule_date_hour',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_description',
            new_name='delschedule_description',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_duration',
            new_name='delschedule_duration',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_id',
            new_name='delschedule_id',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_ip',
            new_name='delschedule_ip',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_meet_link',
            new_name='delschedule_meet_link',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_meet_location',
            new_name='delschedule_meet_location',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_name_creator',
            new_name='delschedule_name_creator',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_name_receiver',
            new_name='delschedule_name_receiver',
        ),
        migrations.RenameField(
            model_name='delschedule',
            old_name='scheduledel_topic',
            new_name='delschedule_topic',
        ),
        migrations.RemoveField(
            model_name='delschedule',
            name='scheduledel_dt_now',
        ),
        migrations.AddField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 21, 55, 25, 651737), verbose_name='Data e hora atuais'),
        ),
    ]
