# Generated by Django 4.2.1 on 2023-06-01 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_rename_scheduledel_browser_delschedule_delschedule_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 0, 44, 21, 812549), verbose_name='Data e hora atuais'),
        ),
    ]
