# Generated by Django 4.2.1 on 2023-06-01 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 17, 46, 22, 999027), verbose_name='Data e hora atuais'),
        ),
    ]
