# Generated by Django 4.2.1 on 2023-06-30 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.BooleanField(default=False, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 3, 3, 7, 447073), verbose_name='Data e hora atuais'),
        ),
    ]
