# Generated by Django 4.2.1 on 2023-06-19 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delschedule',
            name='delschedule_meet_link',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_meet_link',
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 18, 40, 14, 713813), verbose_name='Data e hora atuais'),
        ),
    ]
