# Generated by Django 4.2.1 on 2023-06-30 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_schedule_status_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='delschedule',
            name='delschedule_meet_link',
            field=models.URLField(default='', max_length=150, verbose_name='Link de reunião'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 3, 11, 28, 983088), verbose_name='Data e hora atuais'),
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_topic',
            field=models.CharField(max_length=45, verbose_name='Tópico'),
        ),
    ]
