# Generated by Django 4.2.1 on 2023-06-30 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_delschedule_delschedule_meet_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='status',
            new_name='schedule_status',
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 3, 16, 52, 761520), verbose_name='Data e hora atuais'),
        ),
    ]
