# Generated by Django 4.2.1 on 2023-06-07 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delschedule',
            name='delschedule_topic',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_topic',
        ),
        migrations.AddField(
            model_name='delschedule',
            name='delschedule_title',
            field=models.CharField(default=' ', max_length=30, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_title',
            field=models.CharField(default=' ', max_length=30, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 23, 14, 103962), verbose_name='Data e hora atuais'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date_hour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Hora inicial'),
        ),
    ]
