# Generated by Django 4.2.1 on 2023-06-07 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_remove_delschedule_delschedule_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 23, 47, 395904), verbose_name='Data e hora atuais'),
        ),
    ]
