# Generated by Django 4.2.1 on 2023-06-07 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delschedule',
            name='delschedule_name_receiver',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name_receiver',
        ),
        migrations.AddField(
            model_name='delschedule',
            name='delschedule_name_collaborator',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nome do colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_name_collaborator',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nome do colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 46, 17, 139497), verbose_name='Data e hora atuais'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_meet_link',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Link de reunião'),
        ),
    ]
