# Generated by Django 4.2.1 on 2023-06-14 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_remove_delschedule_delschedule_name_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 9, 1, 6, 623019), verbose_name='Data e hora atuais'),
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_meet_link',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Link de reunião'),
        ),
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_meet_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local da Reunião'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date_hour',
            field=models.DateTimeField(verbose_name='Data Hora inicial'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_meet_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local da Reunião'),
        ),
    ]
