# Generated by Django 4.2.1 on 2023-06-14 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_delschedule_delschedule_dt_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 9, 4, 43, 968684), verbose_name='Data e hora atuais'),
        ),
    ]
