# Generated by Django 4.2.1 on 2023-06-27 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_alter_delschedule_delschedule_dt_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delschedule',
            name='delschedule_dt_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 8, 55, 12, 319516), verbose_name='Data e hora atuais'),
        ),
    ]
