# Generated by Django 4.2.1 on 2023-08-29 00:15

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollaborator',
            fields=[
                ('collaborator_id', models.BigAutoField(default=home.models.UserCollaborator.idColaborador, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_name', models.CharField(max_length=50, verbose_name='NOME')),
                ('collaborator_email', models.EmailField(max_length=255, verbose_name='E-MAIL')),
                ('collaborator_function', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
                ('collaborator_token', models.CharField(default=home.models.UserCollaborator.token, max_length=12, verbose_name='TOKEN')),
                ('collaborator', models.ImageField(upload_to=home.models.UserCollaborator.upload_image, verbose_name='IMAGEM GERENTE')),
            ],
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('manager_id', models.BigAutoField(default=home.models.UserManager.idGerente, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50, verbose_name='NOME')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='E-MAIL')),
                ('manager_function', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
                ('manager_token', models.CharField(default=home.models.UserManager.token, max_length=12, verbose_name='TOKEN')),
                ('manager_image', models.ImageField(upload_to=home.models.UserManager.upload_image, verbose_name='IMAGEM GERENTE')),
            ],
        ),
    ]
