# Generated by Django 4.2.1 on 2023-06-15 01:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollaborator',
            name='collaborator_token',
            field=models.CharField(default=home.models.UserCollaborator.token, max_length=12, verbose_name='TOKEN'),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='manager_token',
            field=models.CharField(default=home.models.UserManager.token, max_length=12, verbose_name='TOKEN'),
        ),
    ]
