# Generated by Django 4.2.1 on 2023-06-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_email',
            new_name='collaborator_email',
        ),
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_function',
            new_name='collaborator_function',
        ),
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_id',
            new_name='collaborator_id',
        ),
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_name',
            new_name='collaborator_name',
        ),
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_password',
            new_name='collaborator_password',
        ),
        migrations.RenameField(
            model_name='usercollaborator',
            old_name='collaborato_token',
            new_name='collaborator_token',
        ),
    ]
