# Generated by Django 4.2.1 on 2023-08-06 18:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollaborator',
            name='collaborator_id',
            field=models.BigAutoField(default=home.models.UserCollaborator.idColaborador, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='manager_id',
            field=models.BigAutoField(default=home.models.UserManager.idGerente, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
