# Generated by Django 4.2.1 on 2023-05-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollaborator',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='SENHA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanager',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='SENHA'),
            preserve_default=False,
        ),
    ]
