# Generated by Django 4.2.1 on 2023-08-01 02:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollaborator',
            name='collaborator',
            field=models.ImageField(default='', upload_to=home.models.UserCollaborator.upload_image, verbose_name='IMAGEM GERENTE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanager',
            name='manager_image',
            field=models.ImageField(default='', upload_to=home.models.UserManager.upload_image, verbose_name='IMAGEM GERENTE'),
            preserve_default=False,
        ),
    ]
