# Generated by Django 4.2.1 on 2023-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usercollaborator_password_usermanager_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollaborator',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
