# Generated by Django 4.2.1 on 2023-06-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usercollaborator_collaborator_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollaborator',
            name='collaborator_password',
        ),
        migrations.RemoveField(
            model_name='usermanager',
            name='manager_password',
        ),
    ]
