# Generated by Django 4.2.1 on 2023-07-26 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logs_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logs_date_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='DATA/HORA')),
                ('logs_desc', models.CharField(max_length=255, verbose_name='DESCRIÇÃO')),
                ('logs_host', models.CharField(max_length=50, verbose_name='HOST')),
            ],
        ),
    ]
